#!/bin/bash

echo "run-vote"

#check number of params
if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    echo "Try somethin like:"
    echo "./run-vote -DserverAddress=​xx.xx.xx.xx:yyyy​ -DvotesPath=​fileName"
    exit
fi

#check content of params -> the best would be to have if el if and else say "sorry params are invalid!"

INPUT=$1
left=$(echo $INPUT| cut -d'=' -f 1)
#echo $left
if [ $left == "-DserverAddress" ]
  then
    SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
elif [ $left == "-DvotesPath" ]
  then
    VOTESPATH=$(echo $INPUT| cut -d'=' -f 2)
else
  echo "Invalid params"
  exit
fi

INPUT=$2
left=$(echo $INPUT| cut -d'=' -f 1)
#echo $left
if [ $left == "-DserverAddress" ]
  then
    SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
elif [ $left == "-DvotesPath" ]
  then
    VOTESPATH=$(echo $INPUT| cut -d'=' -f 2)
else
  echo "Invalid params"
  exit
fi

cd client/target/POD-client-1.0-SNAPSHOT

java $* -cp 'lib/jars/*' "ar.edu.itba.pod.client.VoteClient" $SERVERADRESS $VOTESPATH #$*

#./run-vote -DserverAddress=​xx.xx.xx.xx:yyyy​ -DvotesPath=​fileName

#./run-vote -DserverAddress=10.6.0.1:1099 -DvotesPath=../votos.csv

#./run-vote -DvotesPath=../votos.csv -DserverAddress=10.6.0.1:1099

#./run-vote -DvotesPath=/Users/luciopagni/Desktop -DserverAddress=10.6.0.1