#!/bin/bash

# No se puede hacer una query que haga una búsqueda por state y polling place al mismo tiempo

echo "run-query"

numOfParams="$#"
#echo $numOfParams

if [ "$#" -lt 2 ]; then
    echo "Illegal number of parameters. You have too little params"
    echo "Try somethin like:"
    echo "./run-query -DserverAddress=xx.xx.xx.xx:yyyy​ -Dstate=stateName​ -Did=pollingPlaceNumber -DoutPath=fileName"
    exit
fi

#Si me llegan tanto la provincia como el id entonces tengo que tirar una exepción

#if [ "$#" -gt 4 ]; then
#    echo "Illegal number of parameters. You have too many params"
#    echo "Try somethin like:"
#    echo "./run-query -DserverAddress=xx.xx.xx.xx:yyyy​ -Dstate=stateName​ -Did=pollingPlaceNumber -DoutPath=fileName"
#    exit
#fi

# Esto es necesario hacer porque el query tiene parametros opcionales
# , entonces es posible que tenga el numero adecuado de parámetros, válidos en su contenido
# ; pero que no esten los parámetros mínimos para llevar a adelante la tarea.

hasState=false
hasPollPlaceNum=false
SERVERADRESS="empty" #NO DEBERIA SER EMPTY AL LLAMAR A JAVA
ID="empty"
STATE="empty"
OUTPATH="empty" #NO DEBERIA SER EMPTY AL LLAMAR A JAVA

INPUT=$1
left=$(echo $INPUT| cut -d'=' -f 1)
#echo $left
#SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
if [ $left == "-DserverAddress" ]
  then
    SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
elif [ $left == "-Dstate" ]
  then
    STATE=$(echo $INPUT| cut -d'=' -f 2)
    hasState=true
elif [ $left == "-Did" ]
  then
    ID=$(echo $INPUT| cut -d'=' -f 2)
    hasPollPlaceNum=true
elif [ $left == "-DoutPath" ]
  then
    OUTPATH=$(echo $INPUT| cut -d'=' -f 2)
else
  echo "Invalid params"
  exit
fi

INPUT=$2
left=$(echo $INPUT| cut -d'=' -f 1)
#echo $left
#STATE=$(echo $INPUT| cut -d'=' -f 2)
if [ $left == "-DserverAddress" ]
  then
    SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
elif [ $left == "-Dstate" ]
  then
    STATE=$(echo $INPUT| cut -d'=' -f 2)
    hasState=true
elif [ $left == "-Did" ]
  then
    ID=$(echo $INPUT| cut -d'=' -f 2)
    hasPollPlaceNum=true
elif [ $left == "-DoutPath" ]
  then
    OUTPATH=$(echo $INPUT| cut -d'=' -f 2)
else
  echo "Invalid params"
  exit
fi

if [ $numOfParams -lt 3 ]; then
    cd client/target/POD-client-1.0-SNAPSHOT
    java $* -cp 'lib/jars/*' "ar.edu.itba.pod.client.QueryClient" $SERVERADRESS $STATE $ID $OUTPATH $hasState $hasPollPlaceNum #$*
    exit
fi

INPUT=$3
left=$(echo $INPUT| cut -d'=' -f 1)
#echo $left
#ID=$(echo $INPUT| cut -d'=' -f 2)
if [ $left == "-DserverAddress" ]
  then
    SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
elif [ $left == "-Dstate" ]
  then
    STATE=$(echo $INPUT| cut -d'=' -f 2)
    hasState=true
elif [ $left == "-Did" ]
  then
    ID=$(echo $INPUT| cut -d'=' -f 2)
    hasPollPlaceNum=true
elif [ $left == "-DoutPath" ]
  then
    OUTPATH=$(echo $INPUT| cut -d'=' -f 2)
else
  echo "Invalid params"
  exit
fi

if [ $numOfParams -lt 4 ]; then
    cd client/target/POD-client-1.0-SNAPSHOT
    java $* -cp 'lib/jars/*' "ar.edu.itba.pod.client.QueryClient" $SERVERADRESS $STATE $ID $OUTPATH $hasState $hasPollPlaceNum #$*
    exit
fi

INPUT=$4
left=$(echo $INPUT| cut -d'=' -f 1)
#echo $left
#OUTPATH=$(echo $INPUT| cut -d'=' -f 2)
if [ $left == "-DserverAddress" ]
  then
    SERVERADRESS=$(echo $INPUT| cut -d'=' -f 2)
elif [ $left == "-Dstate" ]
  then
    STATE=$(echo $INPUT| cut -d'=' -f 2)
    hasState=true
elif [ $left == "-Did" ]
  then
    ID=$(echo $INPUT| cut -d'=' -f 2)
    hasPollPlaceNum=true
elif [ $left == "-DoutPath" ]
  then
    OUTPATH=$(echo $INPUT| cut -d'=' -f 2)
else
  echo "Invalid params"
  exit
fi

cd client/target/POD-client-1.0-SNAPSHOT
java $* -cp 'lib/jars/*' "ar.edu.itba.pod.client.QueryClient" $SERVERADRESS $STATE $ID $OUTPATH $hasState $hasPollPlaceNum #$*

#./run-query -DserverAddress=xx.xx.xx.xx:yyyy​ -Dstate=stateName​ -Did=pollingPlaceNumber -DoutPath=fileName

#./run-query -DoutPath=fileName -DserverAddress=xx.xx.xx.xx:yyyy​ -Dstate=stateName​ -Did=pollingPlaceNumber

#./run-query -Did=pollingPlaceNumber -DserverAddress=xx.xx.xx.xx:yyyy​ -Dstate=stateName​ -DoutPath=fileName

#./run-query -Dstate=stateName​ -DserverAddress=xx.xx.xx.xx:yyyy​ -Did=pollingPlaceNumber -DoutPath=fileName

#./run-query -DserverAddress=10.6.0.1:1099 -DoutPath=../query2.csv -Dstate=JUNGLE

#./run-query -DoutPath=../query2.csv -Dstate=JUNGLE -DserverAddress=10.6.0.1:1099

#./run-query -DoutPath=../query2.csv -DserverAddress=10.6.0.1:1099 -Dstate=JUNGLE

#./run-query -DserverAddress=10.6.0.1:1099 -DoutPath=../query2.csv -Dstate=JUNGLE
